1- abre os 2 arquivos 

2- pega as infos necessarias

3 - cria uma aba para cada barco

4 - preenche os dados para cada barco em cada aba

5 - coloca os dados fixos

In [477]:
import openpyxl
import pyautogui
import pandas as pd
PLANILHA = '../assets/EQUIPAMENTOS FROTA.xlsx'

def escreve_formulario(x,y,dados):
    pyautogui.click(x,y, duration = 0.5)
    pyautogui.write(dados)

def get_last_row(planilha):
    return planilha.max_row

def get_index(workbook):
    for index, sheet in enumerate(workbook, start=1):
        sheet.title = f'Aba{index}'


def get_cell(sheet,range):
    sheet[range].value 
    
def ver_planilha(wk_name):
    for row in wk_name.iter_rows(values_only=True):
        print(row)

def preenche_dados(sheet,df,index):
    for row in df.iterrows():
        sheet[f'B{9 + index}'] = row['EQUIPAMENTO']
        sheet[f'D{9 + index}'] = row['FABRICANTE']
        sheet[f'E{9 + index}'] = row['MODELO']



def salvar(wb,name_xlsx):
    wb.save(f'{name_xlsx}.xlsx')
    print(f'Arquivo {name_xlsx} salvo!')

def copiar_aba(wb,nome_old,nome_new):
    sheet_to_copy = wb[nome_old]
    new_sheet = wb.create_sheet(nome_new)
    for row in sheet_to_copy.iter_rows():
        for cell in row:
            #rint(cell)
            new_sheet[cell.coordinate].value = cell.value

def create_sheets(wb,array):
    for i in array:
        wb.create_sheet(title= i)
        wb.save('../assets/Cadastro de Equipamentos - Oilxplorer Marine.xlsx')


def copiar_excel(wb,new_sheet_name):
    source = wb.active
    target = wb.copy_worksheet(source)
    target.title = new_sheet_name
    
    salvar(wb,'copia_teste')

In [443]:
df_equipamentos = pd.read_excel(PLANILHA)
cols = df_equipamentos.columns[:4]

df = df_equipamentos[cols]
df

    EMBARCAÇÃO EQUIPAMENTO FABRICANTE       MODELO
0       C OURO         MCP        CAT        3516B
1       C OURO         MCP        CAT        3516B
2       C OURO         MCA        CAT        3406C
3       C OURO         MCA        CAT        3406C
4       C OURO    AZIMUTAL   SCHOTTEL  SRP 1215 CP
..         ...         ...        ...          ...
376       TITÃ   REVERSORA         ZF        W1900
377    ZANGADO         MCP     SCANIA    DS-11 MO1
378    ZANGADO         MCP     SCANIA    DS-11 MO1
379    ZANGADO   REVERSORA   REINTJES      WAV-121
380    ZANGADO   REVERSORA   REINTJES      WAV-121

[381 rows x 4 columns]

In [444]:
nomes_barcos = list(df['EMBARCAÇÃO'].drop_duplicates())
print(nomes_barcos)

pivot = df.pivot_table(index = 'EMBARCAÇÃO', columns='EQUIPAMENTO',aggfunc='count')
#display(pivot)

['C OURO', 'ATLANTICO', 'AÇU', 'ANGRA', 'ARRAIAL', 'MACAÉ', 'MACEIÓ', 'NITEROI', 'SALVADOR ', 'SEPETIBA', 'VITORIA', 'RIO', 'ITACURUÇA', 'SAGAMORIM II', 'LH COMANDANTE', 'SUPERPESA XIII', 'SUPERPESA XIV', 'ÁGATA', 'ESMERALDA', 'JADE', 'TOPAZIO', 'TURMALINA', 'TURQUESA', 'BRILHANTE', 'CRISTAL', 'DIAMANTE', 'QUARTZO', 'OPALA', 'PEROLA ', 'CICLONE', 'F. ANDREIS XI', 'MERLIM', 'NEBLINA', 'NEW TROVÃO', 'ONIX', 'PERSIVAL', 'TEMPESTADE', 'TORMENTA', 'TORNADO', 'TUFÃO', 'VENDAVAL', 'VENTANIA', 'VIGO MAXIMUS', 'COBRE', 'MERCURIO IV', 'NIQUEL', 'TEMPORAL', 'ADS I', 'CARLA', 'DIALCAR III', 'DIALCAR V', 'FELIZ', 'FLORA', 'MINI ORANGE', 'N.ALMEIDA VII', 'NAVEMAR XIV', 'PRUDENT', 'RELÂMPAGO', 'TITÃ', 'ZANGADO']

In [481]:
df_filtrado = df.loc[df['EMBARCAÇÃO']== nomes_barcos[6]]
df_filtrado

   EMBARCAÇÃO EQUIPAMENTO  FABRICANTE         MODELO
47     MACEIÓ         MCP  MITSUBISHI  S6R2-T2MPTK3L
48     MACEIÓ         MCP  MITSUBISHI  S6R2-T2MPTK3L
49     MACEIÓ         MCP  MITSUBISHI    S12R-T2MPTK
50     MACEIÓ         MCA         MWM          6.10T
51     MACEIÓ         MCA         MWM          6.10T
52     MACEIÓ   REVERSORA   TWIN DISC     MGX 5321DC
53     MACEIÓ   REVERSORA   TWIN DISC     MGX 5321DC
54     MACEIÓ   REVERSORA   TWIN DISC     MGX 5321DC

## PLanilha 2
---

In [446]:
df_cadastro = pd.read_excel('../assets/Cadastro de Equipamentos - Oilxplorer Marine.xlsx',skiprows=6)
df_cadastro.head()

,Nº,Descrição do Equipamento,Lubrificante em uso,Fabricante do Equipamento,Modelo do Equipamento,Vol. (L),Periodicidade de coleta (dias)
0,1,MCP BB (EXAMPLE),Mobil Delvac MX 15W-40,Caterpillar,CAT 3516,800.0,90.0
1,2,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN

In [492]:
for  index, row in df_filtrado.iterrows():
    print(index)
    print(row['EQUIPAMENTO'])

71
MCP
72
MCP
73
MCP
74
MCA
75
MCA
76
REVERSORA
77
REVERSORA
78
REVERSORA

In [496]:
# Carregar a planilha
wb_marine = openpyxl.load_workbook('../assets/Cadastro de Equipamentos - Oilxplorer Marine.xlsx')
sheet = wb_marine['Plan1']  # Substitua pelo nome real da sua aba
nomes_sheets = wb_marine.sheetnames
my_sheet = wb_marine['Plan1']

start_row = 9

for index in range(len(nomes_barcos) -50 ):
    target = wb_marine.copy_worksheet(my_sheet)
    target.title = nomes_barcos[index]
    salvar(wb_marine,'cadastro_marine')

    try:
        planilhas = wb_marine[wb_marine.sheetnames[index+1]]

        if (nomes_barcos[index] == planilhas.title ):
            print(planilhas)
            df_filtrado = df.loc[df['EMBARCAÇÃO']== nomes_barcos[index]]
            print(df_filtrado)
            planilhas['D5'].value = 'PV'
            planilhas['D3'].value = nomes_barcos[index]
            for i, row in df_filtrado.iterrows():
                # Escrevendo os dados nas células correspondentes
                planilhas[f'B{start_row + i}'] = row['EQUIPAMENTO']
                planilhas[f'D{start_row + i}']= row['FABRICANTE']
                planilhas[f'E{start_row + i}'] = row['MODELO']

            wb_marine.save('teste_output.xlsx')


    except IndexError:
        print("Erro")
 
print(wb_marine.sheetnames)

/home/pedrov/.local/lib/python3.11/site-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")

Arquivo cadastro_marine salvo!
<Worksheet "C OURO">
  EMBARCAÇÃO     EQUIPAMENTO FABRICANTE         MODELO
0     C OURO             MCP        CAT          3516B
1     C OURO             MCP        CAT          3516B
2     C OURO             MCA        CAT          3406C
3     C OURO             MCA        CAT          3406C
4     C OURO        AZIMUTAL   SCHOTTEL    SRP 1215 CP
5     C OURO        AZIMUTAL   SCHOTTEL    SRP 1215 CP
6     C OURO    BOW THRUSTER   SCHOTTEL  STT 550 LK CP
7     C OURO    BOW THRUSTER   SCHOTTEL  STT 550 LK CP
8     C OURO  GERADOR EMERG.    WEICHAI       SEM INFO
Arquivo cadastro_marine salvo!
<Worksheet "ATLANTICO">
   EMBARCAÇÃO EQUIPAMENTO FABRICANTE        MODELO
9   ATLANTICO         MCP         GM  2SA EMD645ES
10  ATLANTICO         MCP         GM  2SA EMD645ES
11  ATLANTICO   REVERSORA   REINTJES      SEM INFO
12  ATLANTICO   REVERSORA   REINTJES      SEM INFO
13  ATLANTICO         MCA        MWM         6.10T
14  ATLANTICO         MCA        MWM         6.10T
Arquivo cadastro_marine salvo!
<Worksheet "AÇU">
   EMBARCAÇÃO EQUIPAMENTO  FABRICANTE         MODELO
15        AÇU         MCP  MITSUBISHI  S6R2-T2MPTK3L
16        AÇU         MCP  MITSUBISHI  S6R2-T2MPTK3L
17        AÇU         MCP  MITSUBISHI    S12R-T2MPTK
18        AÇU   REVERSORA   TWIN DISC     MGX 5321DC
19        AÇU   REVERSORA   TWIN DISC     MGX 5321DC
20        AÇU   REVERSORA   TWIN DISC     MGX 5321DC
21        AÇU         MCA         MWM          6.10T
22        AÇU         MCA         MWM          6.10T
Arquivo cadastro_marine salvo!
<Worksheet "ANGRA">
   EMBARCAÇÃO EQUIPAMENTO  FABRICANTE        MODELO
23      ANGRA         MCP  MITSUBISHI  S6R2-T2MPTK3
24      ANGRA         MCP  MITSUBISHI  S6R2-T2MPTK3
25      ANGRA         MCP  MITSUBISHI  S6R2-T2MPTK3
26      ANGRA   REVERSORA          ZF          3755
27      ANGRA   REVERSORA          ZF          3755
28      ANGRA   REVERSORA          ZF          3755
29      ANGRA         MCA     WEICHAI    CCFJ90J-WF
30      ANGRA         MCA     WEICHAI    CCFJ90J-WF
Arquivo cadastro_marine salvo!
<Worksheet "ARRAIAL">
   EMBARCAÇÃO EQUIPAMENTO  FABRICANTE        MODELO
31    ARRAIAL         MCP  MITSUBISHI  S6R2-T2MPTK3
32    ARRAIAL         MCP  MITSUBISHI  S6R2-T2MPTK3
33    ARRAIAL         MCP  MITSUBISHI  S6R2-T2MPTK3
34    ARRAIAL         MCA     WEICHAI    CCFJ90J-WF
35    ARRAIAL         MCA     WEICHAI    CCFJ90J-WF
36    ARRAIAL   REVERSORA          ZF          3755
37    ARRAIAL   REVERSORA          ZF          3755
38    ARRAIAL   REVERSORA          ZF          3755
Arquivo cadastro_marine salvo!
<Worksheet "MACAÉ">
   EMBARCAÇÃO EQUIPAMENTO  FABRICANTE        MODELO
39      MACAÉ         MCP  MITSUBISHI  S6R2-T2MPTK3
40      MACAÉ         MCP  MITSUBISHI  S6R2-T2MPTK3
41      MACAÉ         MCP  MITSUBISHI  S6R2-T2MPTK3
42      MACAÉ         MCA     WEICHAI    CCFJ90J-WF
43      MACAÉ         MCA     WEICHAI    CCFJ90J-WF
44      MACAÉ   REVERSORA          ZF          3755
45      MACAÉ   REVERSORA          ZF          3755
46      MACAÉ   REVERSORA          ZF          3755
Arquivo cadastro_marine salvo!
<Worksheet "MACEIÓ">
   EMBARCAÇÃO EQUIPAMENTO  FABRICANTE         MODELO
47     MACEIÓ         MCP  MITSUBISHI  S6R2-T2MPTK3L
48     MACEIÓ         MCP  MITSUBISHI  S6R2-T2MPTK3L
49     MACEIÓ         MCP  MITSUBISHI    S12R-T2MPTK
50     MACEIÓ         MCA         MWM          6.10T
51     MACEIÓ         MCA         MWM          6.10T
52     MACEIÓ   REVERSORA   TWIN DISC     MGX 5321DC
53     MACEIÓ   REVERSORA   TWIN DISC     MGX 5321DC
54     MACEIÓ   REVERSORA   TWIN DISC     MGX 5321DC
Arquivo cadastro_marine salvo!
<Worksheet "NITEROI">
   EMBARCAÇÃO EQUIPAMENTO  FABRICANTE        MODELO
55    NITEROI         MCP  MITSUBISHI  S6R2-T2MPTK3
56    NITEROI         MCP  MITSUBISHI  S6R2-T2MPTK3
57    NITEROI         MCP  MITSUBISHI  S6R2-T2MPTK3
58    NITEROI         MCA     WEICHAI    CCFJ90J-WF
59    NITEROI         MCA     WEICHAI    CCFJ90J-WF
60    NITEROI   REVERSORA          ZF          3755
61    NITEROI   REVERSORA          ZF          3755
62    NITEROI   REVERSORA          ZF          3755
Arquivo cadastro_marine salvo!
<Worksheet "SALVADOR ">
   EMBARCAÇÃO EQUIPAMENTO  FABRICANTE         MODELO
63  SALVADOR          MCP  MITSUBISHI  S6R2-T2MPTK3L
64  SALVADOR          MCP  MITSUBISHI  S6R2-T2MPTK3L
65  SALVADOR          MCP  MITSUBISHI    S12R-T2MPTK
66  SALVADOR          MCA         MWM          6.10T
67  SALVADOR          MCA         MWM          6.10T
68  SALVADOR    REVERSORA   TWIN DISC     MGX 5321DC
69  SALVADOR    REVERSORA   TWIN DISC     MGX 5321DC
70  SALVADOR    REVERSORA   TWIN DISC     MGX 5321DC
Arquivo cadastro_marine salvo!
<Worksheet "SEPETIBA">
   EMBARCAÇÃO EQUIPAMENTO  FABRICANTE         MODELO
71   SEPETIBA         MCP  MITSUBISHI  S6R2-T2MPTK3L
72   SEPETIBA         MCP  MITSUBISHI  S6R2-T2MPTK3L
73   SEPETIBA         MCP  MITSUBISHI    S12R-T2MPTK
74   SEPETIBA         MCA         MWM          6.10T
75   SEPETIBA         MCA         MWM          6.10T
76   SEPETIBA   REVERSORA   TWIN DISC     MGX 5321DC
77   SEPETIBA   REVERSORA   TWIN DISC     MGX 5321DC
78   SEPETIBA   REVERSORA   TWIN DISC     MGX 5321DC
['Plan1', 'C OURO', 'ATLANTICO', 'AÇU', 'ANGRA', 'ARRAIAL', 'MACAÉ', 'MACEIÓ', 'NITEROI', 'SALVADOR ', 'SEPETIBA']

In [471]:

wb_marine = openpyxl.load_workbook('../assets/Cadastro de Equipamentos - Oilxplorer Marine.xlsx')

for index in range(0,len(nomes_barcos) - 25):
    print(wb_marine.sheetnames[index+1])

    planilhas = wb_marine[wb_marine.sheetnames[index+1]]
    print(planilhas)
    print(nomes_barcos[index])        
    #wb_marine.save('teste_output.xlsx')

IndexError: list index out of range

In [480]:

# Começar a escrever a partir da linha 9
start_row = 9
for index, row in df.iterrows():
    # Escrevendo os dados nas células correspondentes
    sheet[f'B{start_row + index}'] = row['EQUIPAMENTO']
    sheet[f'D{start_row + index}'] = row['FABRICANTE']
    sheet[f'E{start_row + index}'] = row['MODELO']
    #sheet['D3'].value = nomes_barcos[index]

    


# Salvar a planilha
wb_marine.save('output.xlsx',)

In [452]:

def roboPreencheCadastro(PLANILHA):

    workbook = openpyxl.load_workbook(PLANILHA)
    planilha = workbook['OverView IFS']
    _array = []

    lastRow = get_last_row(planilha)

    for row in planilha.iter_rows(min_row = 2,max_row=6):

        # COluna1 , Coluna 2, Coluna 3
        equipamento = row[1].value
        print(equipamento)
        escreve_formulario(1149,178,equipamento)

        rebocador = row[0].value
        escreve_formulario(1150,246,rebocador)

        acao = row[2].value
        escreve_formulario(1150,323,acao)

        status = row[3].value
        escreve_formulario(1150,370,status)

        tipo = row[4].value
        escreve_formulario(1160,467,tipo)

        pyautogui.click(1319,724)