1- abre os 2 arquivos 

2- pega as infos necessarias

3 - cria uma aba para cada barco

4 - preenche os dados para cada barco em cada aba

5 - coloca os dados fixos

In [392]:
import openpyxl
import pyautogui
import pandas as pd
PLANILHA = '../assets/EQUIPAMENTOS FROTA.xlsx'

def escreve_formulario(x,y,dados):
    pyautogui.click(x,y, duration = 0.5)
    pyautogui.write(dados)

def get_last_row(planilha):
    return planilha.max_row

def get_index(workbook):
    for index, sheet in enumerate(workbook, start=1):
        sheet.title = f'Aba{index}'


def get_cell(sheet,range):
    sheet[range].value 


def salvar(wb,name_xlsx):
    wb.save(f'{name_xlsx}.xlsx')
    print(f'Arquivo {name_xlsx} salvo!')

def copiar_aba(wb,nome_old,nome_new):
    sheet_to_copy = wb[nome_old]
    new_sheet = wb.create_sheet(nome_new)
    for row in sheet_to_copy.iter_rows():
        for cell in row:
            #rint(cell)
            new_sheet[cell.coordinate].value = cell.value


def copiar_excel(wb,new_sheet_name):
    source = wb.active
    target = wb.copy_worksheet(source)
    target.title = new_sheet_name
    
    salvar(wb,'copia_teste')

In [393]:
df_equipamentos = pd.read_excel(PLANILHA)
cols = df_equipamentos.columns[:4]

df = df_equipamentos[cols]
df

    EMBARCAÇÃO EQUIPAMENTO FABRICANTE       MODELO
0       C OURO         MCP        CAT        3516B
1       C OURO         MCP        CAT        3516B
2       C OURO         MCA        CAT        3406C
3       C OURO         MCA        CAT        3406C
4       C OURO    AZIMUTAL   SCHOTTEL  SRP 1215 CP
..         ...         ...        ...          ...
376       TITÃ   REVERSORA         ZF        W1900
377    ZANGADO         MCP     SCANIA    DS-11 MO1
378    ZANGADO         MCP     SCANIA    DS-11 MO1
379    ZANGADO   REVERSORA   REINTJES      WAV-121
380    ZANGADO   REVERSORA   REINTJES      WAV-121

[381 rows x 4 columns]

In [394]:
nomes_barcos = list(df['EMBARCAÇÃO'].drop_duplicates())
print(nomes_barcos)

pivot = df.pivot_table(index = 'EMBARCAÇÃO', columns='EQUIPAMENTO',aggfunc='count')
#display(pivot)

['C OURO', 'ATLANTICO', 'AÇU', 'ANGRA', 'ARRAIAL', 'MACAÉ', 'MACEIÓ', 'NITEROI', 'SALVADOR ', 'SEPETIBA', 'VITORIA', 'RIO', 'ITACURUÇA', 'SAGAMORIM II', 'LH COMANDANTE', 'SUPERPESA XIII', 'SUPERPESA XIV', 'ÁGATA', 'ESMERALDA', 'JADE', 'TOPAZIO', 'TURMALINA', 'TURQUESA', 'BRILHANTE', 'CRISTAL', 'DIAMANTE', 'QUARTZO', 'OPALA', 'PEROLA ', 'CICLONE', 'F. ANDREIS XI', 'MERLIM', 'NEBLINA', 'NEW TROVÃO', 'ONIX', 'PERSIVAL', 'TEMPESTADE', 'TORMENTA', 'TORNADO', 'TUFÃO', 'VENDAVAL', 'VENTANIA', 'VIGO MAXIMUS', 'COBRE', 'MERCURIO IV', 'NIQUEL', 'TEMPORAL', 'ADS I', 'CARLA', 'DIALCAR III', 'DIALCAR V', 'FELIZ', 'FLORA', 'MINI ORANGE', 'N.ALMEIDA VII', 'NAVEMAR XIV', 'PRUDENT', 'RELÂMPAGO', 'TITÃ', 'ZANGADO']

In [395]:
df_filtrado = df.loc[df['EMBARCAÇÃO']== nomes_barcos[6]]
df_filtrado

   EMBARCAÇÃO EQUIPAMENTO  FABRICANTE         MODELO
47     MACEIÓ         MCP  MITSUBISHI  S6R2-T2MPTK3L
48     MACEIÓ         MCP  MITSUBISHI  S6R2-T2MPTK3L
49     MACEIÓ         MCP  MITSUBISHI    S12R-T2MPTK
50     MACEIÓ         MCA         MWM          6.10T
51     MACEIÓ         MCA         MWM          6.10T
52     MACEIÓ   REVERSORA   TWIN DISC     MGX 5321DC
53     MACEIÓ   REVERSORA   TWIN DISC     MGX 5321DC
54     MACEIÓ   REVERSORA   TWIN DISC     MGX 5321DC

## PLanilha 2
---

In [396]:
df_cadastro = pd.read_excel('../assets/Cadastro de Equipamentos - Oilxplorer Marine.xlsx',skiprows=6)
df_cadastro.head()

,Nº,Descrição do Equipamento,Lubrificante em uso,Fabricante do Equipamento,Modelo do Equipamento,Vol. (L),Periodicidade de coleta (dias)
0,1,MCP BB (EXAMPLE),Mobil Delvac MX 15W-40,Caterpillar,CAT 3516,800.0,90.0
1,2,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN

In [397]:
# Carregar a planilha
wb_marine = openpyxl.load_workbook('../assets/Cadastro de Equipamentos - Oilxplorer Marine.xlsx')
sheet = wb_marine['Plan1']  # Substitua pelo nome real da sua aba
nomes_sheets = wb_marine.sheetnames

#wb_marine.copy_worksheet(source_id=wb_marine['SEPETIBA'], target_id=wb_marine['Plan1'])

def colocarAbasArray(nomes_barcos)
    for n in nomes_barcos:
        wb_marine.create_sheet(title= n)
        wb_marine.save('../assets/Cadastro de Equipamentos - Oilxplorer Marine.xlsx')
        
print(wb_marine.sheetnames)

/home/pedrov/.local/lib/python3.11/site-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")

['Plan1', 'C OURO', 'ATLANTICO', 'AÇU', 'ANGRA', 'ARRAIAL', 'MACAÉ', 'MACEIÓ', 'NITEROI', 'SALVADOR ', 'SEPETIBA', 'VITORIA', 'RIO', 'ITACURUÇA', 'SAGAMORIM II', 'LH COMANDANTE', 'SUPERPESA XIII', 'SUPERPESA XIV', 'ÁGATA', 'ESMERALDA', 'JADE', 'TOPAZIO', 'TURMALINA', 'TURQUESA', 'BRILHANTE', 'CRISTAL', 'DIAMANTE', 'QUARTZO', 'OPALA', 'PEROLA ', 'CICLONE', 'F. ANDREIS XI', 'MERLIM', 'NEBLINA', 'NEW TROVÃO', 'ONIX', 'PERSIVAL', 'TEMPESTADE', 'TORMENTA', 'TORNADO', 'TUFÃO', 'VENDAVAL', 'VENTANIA', 'VIGO MAXIMUS', 'COBRE', 'MERCURIO IV', 'NIQUEL', 'TEMPORAL', 'ADS I', 'CARLA', 'DIALCAR III', 'DIALCAR V', 'FELIZ', 'FLORA', 'MINI ORANGE', 'N.ALMEIDA VII', 'NAVEMAR XIV', 'PRUDENT', 'RELÂMPAGO', 'TITÃ', 'ZANGADO']

In [406]:

wb = openpyxl.load_workbook('./copia_teste.xlsx')



copiar_excel(wb,wb['AÇU'].title)

Arquivo copia_teste salvo!

In [400]:

wb_marine = openpyxl.load_workbook('../assets/Cadastro de Equipamentos - Oilxplorer Marine.xlsx')

for index in range(0,len(nomes_barcos) - 25):
    print(wb_marine.sheetnames[index+1])

    planilhas = wb_marine[wb_marine.sheetnames[index+1]]
    print(planilhas)
    print(nomes_barcos[index])        
    #wb_marine.save('teste_output.xlsx')

C OURO
<Worksheet "C OURO">
C OURO
Arquivo copia_teste salvo!
ATLANTICO
<Worksheet "ATLANTICO">
ATLANTICO
Arquivo copia_teste salvo!
AÇU
<Worksheet "AÇU">
AÇU
Arquivo copia_teste salvo!
ANGRA
<Worksheet "ANGRA">
ANGRA
Arquivo copia_teste salvo!
ARRAIAL
<Worksheet "ARRAIAL">
ARRAIAL
Arquivo copia_teste salvo!
MACAÉ
<Worksheet "MACAÉ">
MACAÉ
Arquivo copia_teste salvo!
MACEIÓ
<Worksheet "MACEIÓ">
MACEIÓ
Arquivo copia_teste salvo!
NITEROI
<Worksheet "NITEROI">
NITEROI
Arquivo copia_teste salvo!
SALVADOR
<Worksheet "SALVADOR ">
SALVADOR
Arquivo copia_teste salvo!
SEPETIBA
<Worksheet "SEPETIBA">
SEPETIBA
Arquivo copia_teste salvo!
VITORIA
<Worksheet "VITORIA">
VITORIA
Arquivo copia_teste salvo!
RIO
<Worksheet "RIO">
RIO
Arquivo copia_teste salvo!
ITACURUÇA
<Worksheet "ITACURUÇA">
ITACURUÇA
Arquivo copia_teste salvo!
SAGAMORIM II
<Worksheet "SAGAMORIM II">
SAGAMORIM II
Arquivo copia_teste salvo!
LH COMANDANTE
<Worksheet "LH COMANDANTE">
LH COMANDANTE
Arquivo copia_teste salvo!
SUPERPESA XIII
<Worksheet "SUPERPESA XIII">
SUPERPESA XIII
Arquivo copia_teste salvo!
SUPERPESA XIV
<Worksheet "SUPERPESA XIV">
SUPERPESA XIV
Arquivo copia_teste salvo!
ÁGATA
<Worksheet "ÁGATA">
ÁGATA
Arquivo copia_teste salvo!
ESMERALDA
<Worksheet "ESMERALDA">
ESMERALDA
Arquivo copia_teste salvo!
JADE
<Worksheet "JADE">
JADE
Arquivo copia_teste salvo!
TOPAZIO
<Worksheet "TOPAZIO">
TOPAZIO
Arquivo copia_teste salvo!
TURMALINA
<Worksheet "TURMALINA">
TURMALINA
Arquivo copia_teste salvo!
TURQUESA
<Worksheet "TURQUESA">
TURQUESA
Arquivo copia_teste salvo!
BRILHANTE
<Worksheet "BRILHANTE">
BRILHANTE
Arquivo copia_teste salvo!
CRISTAL
<Worksheet "CRISTAL">
CRISTAL
Arquivo copia_teste salvo!
DIAMANTE
<Worksheet "DIAMANTE">
DIAMANTE
Arquivo copia_teste salvo!
QUARTZO
<Worksheet "QUARTZO">
QUARTZO
Arquivo copia_teste salvo!
OPALA
<Worksheet "OPALA">
OPALA
Arquivo copia_teste salvo!
PEROLA
<Worksheet "PEROLA ">
PEROLA
Arquivo copia_teste salvo!
CICLONE
<Worksheet "CICLONE">
CICLONE
Arquivo copia_teste salvo!
F. ANDREIS XI
<Worksheet "F. ANDREIS XI">
F. ANDREIS XI
Arquivo copia_teste salvo!
MERLIM
<Worksheet "MERLIM">
MERLIM
Arquivo copia_teste salvo!
NEBLINA
<Worksheet "NEBLINA">
NEBLINA
Arquivo copia_teste salvo!
NEW TROVÃO
<Worksheet "NEW TROVÃO">
NEW TROVÃO
Arquivo copia_teste salvo!
ONIX
<Worksheet "ONIX">
ONIX
Arquivo copia_teste salvo!

In [399]:

def preenche_dados(sheet,df):
    for row in df.iterrows():
        sheet[f'B{9 + index}'] = row['EQUIPAMENTO']
        sheet[f'D{9 + index}'] = row['FABRICANTE']
        sheet[f'E{9 + index}'] = row['MODELO']

for index in range(0,len(nomes_barcos)-45):
    try:
        planilhas = wb_marine[wb_marine.sheetnames[index+1]]

        #copiar_excel(wb_marine,nomes_barcos[index] )


        if (nomes_barcos[index] == planilhas.title ):
            planilhas['D5'].value = 'PV'
            planilhas['D3'].value = nomes_barcos[index]


  
        wb_marine.save('teste_output.xlsx')


    except IndexError:
        print("Erro")
        continue

Arquivo copia_teste salvo!

KeyboardInterrupt:

In [ ]:
def ver_planilha(wk_name):
    for row in wk_name.iter_rows(values_only=True):
        print(row)

In [ ]:

# Começar a escrever a partir da linha 9
start_row = 9
for index, row in df.iterrows():
    # Escrevendo os dados nas células correspondentes
    sheet[f'B{start_row + index}'] = row['EQUIPAMENTO']
    sheet[f'D{start_row + index}'] = row['FABRICANTE']
    sheet[f'E{start_row + index}'] = row['MODELO']
    #sheet['D3'].value = nomes_barcos[index]

    


# Salvar a planilha
wb_marine.save('output.xlsx',)

In [ ]:

def roboPreencheCadastro(PLANILHA):

    workbook = openpyxl.load_workbook(PLANILHA)
    planilha = workbook['OverView IFS']
    _array = []

    lastRow = get_last_row(planilha)

    for row in planilha.iter_rows(min_row = 2,max_row=6):

        # COluna1 , Coluna 2, Coluna 3
        equipamento = row[1].value
        print(equipamento)
        escreve_formulario(1149,178,equipamento)

        rebocador = row[0].value
        escreve_formulario(1150,246,rebocador)

        acao = row[2].value
        escreve_formulario(1150,323,acao)

        status = row[3].value
        escreve_formulario(1150,370,status)

        tipo = row[4].value
        escreve_formulario(1160,467,tipo)

        pyautogui.click(1319,724)