In [1]:
import openpyxl
import pyautogui
import pandas as pd
PLANILHA = '../assets/EQUIPAMENTOS FROTA.xlsx'

def escreve_formulario(x,y,dados):
    pyautogui.click(x,y, duration = 0.5)
    pyautogui.write(dados)

def get_last_row(planilha):
    return planilha.max_row

In [2]:
df_equipamentos = pd.read_excel(PLANILHA)
cols = df_equipamentos.columns[:4]

df = df_equipamentos[cols]
df

    EMBARCAÇÃO EQUIPAMENTO FABRICANTE       MODELO
0       C OURO         MCP        CAT        3516B
1       C OURO         MCP        CAT        3516B
2       C OURO         MCA        CAT        3406C
3       C OURO         MCA        CAT        3406C
4       C OURO    AZIMUTAL   SCHOTTEL  SRP 1215 CP
..         ...         ...        ...          ...
376       TITÃ   REVERSORA         ZF        W1900
377    ZANGADO         MCP     SCANIA    DS-11 MO1
378    ZANGADO         MCP     SCANIA    DS-11 MO1
379    ZANGADO   REVERSORA   REINTJES      WAV-121
380    ZANGADO   REVERSORA   REINTJES      WAV-121

[381 rows x 4 columns]

In [3]:
df_cadastro = pd.read_excel('../assets/Cadastro de Equipamentos - Oilxplorer Marine.xlsx',skiprows=6)
df_cadastro.head()

,Nº,Descrição do Equipamento,Lubrificante em uso,Fabricante do Equipamento,Modelo do Equipamento,Vol. (L),Periodicidade de coleta (dias)
0,1,MCP BB (EXAMPLE),Mobil Delvac MX 15W-40,Caterpillar,CAT 3516,800.0,90.0
1,2,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Carregar a planilha
workbook = openpyxl.load_workbook('../assets/Cadastro de Equipamentos - Oilxplorer Marine.xlsx')
sheet = workbook['Plan1']  # Substitua pelo nome real da sua aba

# Começar a escrever a partir da linha 9
start_row = 9
for index, row in df.iterrows():
    # Escrevendo os dados nas células correspondentes
    sheet[f'B{start_row + index}'] = row['EQUIPAMENTO']
    sheet[f'C{start_row + index}'] = row['EMBARCAÇÃO']
    sheet[f'D{start_row + index}'] = row['FABRICANTE']
    sheet[f'E{start_row + index}'] = row['MODELO']
    # Adicione mais células conforme necessário

# Salvar a planilha
workbook.save('output.xlsx')

/home/pedrov/.local/lib/python3.11/site-packages/openpyxl/reader/drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.
  warn("DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.")

In [5]:
# Mapear as informações do df1 para o df2
for index, row in df_equipamentos.iterrows():
    # Encontre a linha correspondente em df2 (ajuste a condição conforme necessário)
    correspondente = df_cadastro[df_cadastro['Descrição do Equipamento'].str.contains(row['EQUIPAMENTO'], na=False)]
    if not correspondente.empty:
        df2_index = correspondente.index[0]
        df_cadastro.at[df2_index, 'Lubrificante em uso'] = 'O lubrificante que deseja'
        df_cadastro.at[df2_index, 'Fabricante do Equipamento'] = row['FABRICANTE']
        df_cadastro.at[df2_index, 'Modelo do Equipamento'] = row['MODELO']
        # Continue com outros campos conforme necessário

# Salvar a planilha atualizada
with pd.ExcelWriter('caminho_para_planilha.xlsx', engine='openpyxl') as writer:
    df_cadastro.to_excel(writer, sheet_name='Nome_da_Aba', index=False)

In [6]:

def roboPreencheCadastro(PLANILHA):

    workbook = openpyxl.load_workbook(PLANILHA)
    planilha = workbook['OverView IFS']
    _array = []

    lastRow = get_last_row(planilha)

    for row in planilha.iter_rows(min_row = 2,max_row=6):

        # COluna1 , Coluna 2, Coluna 3
        equipamento = row[1].value
        print(equipamento)
        escreve_formulario(1149,178,equipamento)

        rebocador = row[0].value
        escreve_formulario(1150,246,rebocador)

        acao = row[2].value
        escreve_formulario(1150,323,acao)

        status = row[3].value
        escreve_formulario(1150,370,status)

        tipo = row[4].value
        escreve_formulario(1160,467,tipo)

        pyautogui.click(1319,724)